---
name: Create Project

on:
  workflow_dispatch:

  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ${{matrix.system}}
    strategy:
      matrix:
        python-version:
          - "3.13"
        system:
          - ubuntu-24.04
    env:
      PYTHON_VERSION: ${{matrix.python-version}}

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - uses: seanmiddleditch/gha-setup-ninja@master

      # - name: setup clang 19
      #   run: |
      #     wget https://apt.llvm.org/llvm.sh
      #     chmod +x ./llvm.sh
      #     sudo ./llvm.sh 19
      #     rm llvm.sh

      - run: sudo apt-get install gcc-14 g++-14 lcov clang-19 clang-format-19

      - name: python${{matrix.python-version}} setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - run: pip${{matrix.python-version}} install vmklib>=2.0.7 yambs>=3.1.1 ifgen>=4.4.3

      - run: mk --version
      - run: mbs --version
      - run: ig --version

      - run: mk test yaml
